<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Xuexitest .proto

namespace Xuexitest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *TestReply ÏìÓ¦½á¹¹
 *
 * Generated from protobuf message <code>xuexitest.TestReply</code>
 */
class TestReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xuexitest.TestReply.GetData getdataarr = 1;</code>
     */
    private $getdataarr;

    public function __construct() {
        \GPBMetadata\Xuexitest::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .xuexitest.TestReply.GetData getdataarr = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGetdataarr()
    {
        return $this->getdataarr;
    }

    /**
     * Generated from protobuf field <code>repeated .xuexitest.TestReply.GetData getdataarr = 1;</code>
     * @param \Xuexitest\TestReply_GetData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGetdataarr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xuexitest\TestReply_GetData::class);
        $this->getdataarr = $arr;

        return $this;
    }

}

